name: Exibir informações da Issue

on:
  issues:
    types: [opened, edited]
    

jobs:
  mostrar-info:
    runs-on: ubuntu-latest
    env:
      NOME_ARQUIVO: issue_data.json
    steps:
      - name: Verificar checkout do repositório
        uses: actions/checkout@v6

      - name: Converter issue para JSON
        uses: zentered/issue-forms-body-parser@v2.2.0
        id: parse

      - name: Salvar dados da issue em um arquivo
        run: |
          echo '${{ steps.parse.outputs.data }}' > $NOME_ARQUIVO
        
  
          echo "Número da issue: ${{ github.event.issue.number }}"
          echo "Labels: ${{ toJson(github.event.issue.labels) }}"

      - name: Executar script para validar evento
        run: |
          python3 -m backend.validar_evento ${{github.workspace}}/$NOME_ARQUIVO

      - name: Executar script de adicionar evento
        run: |
          python3 -m backend.adicionar_evento ${{github.workspace}}/$NOME_ARQUIVO
      
      - name: Criar branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git branch -C adicionar-evento-issue-${{ github.event.issue.number }}
          git switch adicionar-evento-issue-${{ github.event.issue.number }}   

      - name: Commit e push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add backend/eventos.json
          git commit -m "Adicionar evento para issue #${{ github.event.issue.number }}"
          git push -u origin adicionar-evento-issue-${{ github.event.issue.number }}
      
      - name: Criar Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "Adicionar evento para issue #${{ github.event.issue.number }}" \
            --body "Este PR adiciona um evento para a issue #${{ github.event.issue.number }}." \
            --head adicionar-evento-issue-${{ github.event.issue.number }} \
            --base main

